require "assaydepot/version"
require "assaydepot/configurable"
require "assaydepot/client"
require "assaydepot/model"
require "assaydepot/ware"
require "assaydepot/provider"
require "assaydepot/core"
